# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mrpc-mt4-error.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("mrpc-mt4-error.proto", :syntax => :proto3) do
    add_message "mt4_term_api.Error" do
      optional :type, :enum, 1, "mt4_term_api.ErrorType"
      optional :error_code, :string, 2
      optional :error_message, :string, 3
      optional :mql_error_code, :enum, 4, "mt4_term_api.MqlErrorCode"
      optional :mql_error_int_code, :int32, 5
      optional :mql_error_description, :string, 6
      optional :stack_trace, :string, 10
      optional :command_type_name, :string, 11
      optional :commandId, :int64, 12
      repeated :properties, :message, 13, "mt4_term_api.ErrorProperty"
    end
    add_message "mt4_term_api.ErrorProperty" do
      optional :error_arg_key, :string, 1
      optional :error_arg_value, :string, 2
    end
    add_message "mt4_term_api.LogFileInfo" do
      optional :log_type, :enum, 1, "mt4_term_api.LogType"
      optional :full_path, :string, 2
      optional :name, :string, 3
      optional :content, :string, 4
    end
    add_enum "mt4_term_api.LogType" do
      value :Global, 0
      value :MQL5, 1
      value :MQL4, 2
    end
    add_enum "mt4_term_api.ErrorType" do
      value :UNDEFINED, 0
      value :MRPC, 1
      value :MRPC_VALIDATION, 2
      value :MRPC_TIMEOUT, 3
      value :TERMINAL_API_TIMEOUT, 4
      value :TERMINAL_API_GET_PARAMS, 5
      value :TERMINAL_API_SET_RESULT, 6
      value :TERMINAL_API_UNEXPECTED, 7
      value :MQL_EXECUTION, 8
      value :MQL_CUSTOM_EXECUTION, 9
    end
    add_enum "mt4_term_api.MqlErrorCode" do
      value :ERR_NO_ERROR, 0
      value :ERR_NO_RESULT, 1
      value :ERR_COMMON_ERROR, 2
      value :ERR_INVALID_TRADE_PARAMETERS, 3
      value :ERR_SERVER_BUSY, 4
      value :ERR_OLD_VERSION, 5
      value :ERR_NO_CONNECTION, 6
      value :ERR_NOT_ENOUGH_RIGHTS, 7
      value :ERR_TOO_FREQUENT_REQUESTS, 8
      value :ERR_MALFUNCTIONAL_TRADE, 9
      value :ERR_ACCOUNT_DISABLED, 64
      value :ERR_INVALID_ACCOUNT, 65
      value :ERR_TRADE_TIMEOUT, 128
      value :ERR_INVALID_PRICE, 129
      value :ERR_INVALID_STOPS, 130
      value :ERR_INVALID_TRADE_VOLUME, 131
      value :ERR_MARKET_CLOSED, 132
      value :ERR_TRADE_DISABLED, 133
      value :ERR_NOT_ENOUGH_MONEY, 134
      value :ERR_PRICE_CHANGED, 135
      value :ERR_OFF_QUOTES, 136
      value :ERR_BROKER_BUSY, 137
      value :ERR_REQUOTE, 138
      value :ERR_ORDER_LOCKED, 139
      value :ERR_LONG_POSITIONS_ONLY_ALLOWED, 140
      value :ERR_TOO_MANY_REQUESTS, 141
      value :ERR_TRADE_MODIFY_DENIED, 145
      value :ERR_TRADE_CONTEXT_BUSY, 146
      value :ERR_TRADE_EXPIRATION_DENIED, 147
      value :ERR_TRADE_TOO_MANY_ORDERS, 148
      value :ERR_TRADE_HEDGE_PROHIBITED, 149
      value :ERR_TRADE_PROHIBITED_BY_FIFO, 150
      value :ERR_NO_MQLERROR, 4000
      value :ERR_WRONG_FUNCTION_POINTER, 4001
      value :ERR_ARRAY_INDEX_OUT_OF_RANGE, 4002
      value :ERR_NO_MEMORY_FOR_CALL_STACK, 4003
      value :ERR_RECURSIVE_STACK_OVERFLOW, 4004
      value :ERR_NOT_ENOUGH_STACK_FOR_PARAM, 4005
      value :ERR_NO_MEMORY_FOR_PARAM_STRING, 4006
      value :ERR_NO_MEMORY_FOR_TEMP_STRING, 4007
      value :ERR_NOT_INITIALIZED_STRING, 4008
      value :ERR_NOT_INITIALIZED_ARRAYSTRING, 4009
      value :ERR_NO_MEMORY_FOR_ARRAYSTRING, 4010
      value :ERR_TOO_LONG_STRING, 4011
      value :ERR_REMAINDER_FROM_ZERO_DIVIDE, 4012
      value :ERR_ZERO_DIVIDE, 4013
      value :ERR_UNKNOWN_COMMAND, 4014
      value :ERR_WRONG_JUMP, 4015
      value :ERR_NOT_INITIALIZED_ARRAY, 4016
      value :ERR_DLL_CALLS_NOT_ALLOWED, 4017
      value :ERR_CANNOT_LOAD_LIBRARY, 4018
      value :ERR_CANNOT_CALL_FUNCTION, 4019
      value :ERR_EXTERNAL_CALLS_NOT_ALLOWED, 4020
      value :ERR_NO_MEMORY_FOR_RETURNED_STR, 4021
      value :ERR_SYSTEM_BUSY, 4022
      value :ERR_DLLFUNC_CRITICALERROR, 4023
      value :ERR_INTERNAL_ERROR, 4024
      value :ERR_OUT_OF_MEMORY, 4025
      value :ERR_INVALID_POINTER, 4026
      value :ERR_FORMAT_TOO_MANY_FORMATTERS, 4027
      value :ERR_FORMAT_TOO_MANY_PARAMETERS, 4028
      value :ERR_ARRAY_INVALID, 4029
      value :ERR_CHART_NOREPLY, 4030
      value :ERR_INVALID_FUNCTION_PARAMSCNT, 4050
      value :ERR_INVALID_FUNCTION_PARAMVALUE, 4051
      value :ERR_STRING_FUNCTION_INTERNAL, 4052
      value :ERR_SOME_ARRAY_ERROR, 4053
      value :ERR_INCORRECT_SERIESARRAY_USING, 4054
      value :ERR_CUSTOM_INDICATOR_ERROR, 4055
      value :ERR_INCOMPATIBLE_ARRAYS, 4056
      value :ERR_GLOBAL_VARIABLES_PROCESSING, 4057
      value :ERR_GLOBAL_VARIABLE_NOT_FOUND, 4058
      value :ERR_FUNC_NOT_ALLOWED_IN_TESTING, 4059
      value :ERR_FUNCTION_NOT_CONFIRMED, 4060
      value :ERR_SEND_MAIL_ERROR, 4061
      value :ERR_STRING_PARAMETER_EXPECTED, 4062
      value :ERR_INTEGER_PARAMETER_EXPECTED, 4063
      value :ERR_DOUBLE_PARAMETER_EXPECTED, 4064
      value :ERR_ARRAY_AS_PARAMETER_EXPECTED, 4065
      value :ERR_HISTORY_WILL_UPDATED, 4066
      value :ERR_TRADE_ERROR, 4067
      value :ERR_RESOURCE_NOT_FOUND, 4068
      value :ERR_RESOURCE_NOT_SUPPORTED, 4069
      value :ERR_RESOURCE_DUPLICATED, 4070
      value :ERR_INDICATOR_CANNOT_INIT, 4071
      value :ERR_INDICATOR_CANNOT_LOAD, 4072
      value :ERR_NO_HISTORY_DATA, 4073
      value :ERR_NO_MEMORY_FOR_HISTORY, 4074
      value :ERR_NO_MEMORY_FOR_INDICATOR, 4075
      value :ERR_END_OF_FILE, 4099
      value :ERR_SOME_FILE_ERROR, 4100
      value :ERR_WRONG_FILE_NAME, 4101
      value :ERR_TOO_MANY_OPENED_FILES, 4102
      value :ERR_CANNOT_OPEN_FILE, 4103
      value :ERR_INCOMPATIBLE_FILEACCESS, 4104
      value :ERR_NO_ORDER_SELECTED, 4105
      value :ERR_UNKNOWN_SYMBOL, 4106
      value :ERR_INVALID_PRICE_PARAM, 4107
      value :ERR_INVALID_TICKET, 4108
      value :ERR_TRADE_NOT_ALLOWED, 4109
      value :ERR_LONGS_NOT_ALLOWED, 4110
      value :ERR_SHORTS_NOT_ALLOWED, 4111
      value :ERR_TRADE_EXPERT_DISABLED_BY_SERVER, 4112
      value :ERR_OBJECT_ALREADY_EXISTS, 4200
      value :ERR_UNKNOWN_OBJECT_PROPERTY, 4201
      value :ERR_OBJECT_DOES_NOT_EXIST, 4202
      value :ERR_UNKNOWN_OBJECT_TYPE, 4203
      value :ERR_NO_OBJECT_NAME, 4204
      value :ERR_OBJECT_COORDINATES_ERROR, 4205
      value :ERR_NO_SPECIFIED_SUBWINDOW, 4206
      value :ERR_SOME_OBJECT_ERROR, 4207
      value :ERR_FILE_CANNOT_OPEN, 5004
    end
  end
end

module Mt4TermApi
  Error = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.Error").msgclass
  ErrorProperty = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.ErrorProperty").msgclass
  LogFileInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.LogFileInfo").msgclass
  LogType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.LogType").enummodule
  ErrorType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.ErrorType").enummodule
  MqlErrorCode = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.MqlErrorCode").enummodule
end
