# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: mt4-term-api-health-check.proto for package 'mt4_term_api'

require 'grpc'
require 'mt4-term-api-health-check_pb'

module Mt4TermApi
  module HealthService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'mt4_term_api.HealthService'

      rpc :HealthCheck, ::Mt4TermApi::HealthCheckRequest, ::Mt4TermApi::HealthCheckReply
      rpc :CloseTerminal, ::Mt4TermApi::CloseTerminalRequest, ::Mt4TermApi::CloseTerminalReply
    end

    Stub = Service.rpc_stub_class
  end
end
