# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: mt4-term-api-internal-charts.proto for package 'mt4_term_api'

require 'grpc'
require 'mt4-term-api-internal-charts_pb'

module Mt4TermApi
  module InternalCharts
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'mt4_term_api.InternalCharts'

      rpc :ChartOpen, ::Mt4TermApi::ChartOpenRequest, ::Mt4TermApi::ChartOpenReply
      rpc :ChartClose, ::Mt4TermApi::ChartCloseRequest, ::Mt4TermApi::ChartCloseReply
      rpc :CustomChartOpen, ::Mt4TermApi::CustomChartOpenRequest, ::Mt4TermApi::CustomChartOpenReply
      rpc :CustomChartSaveTemplate, ::Mt4TermApi::CustomChartSaveTemplateRequest, ::Mt4TermApi::CustomChartSaveTemplateReply
      rpc :CustomChartApplyTemplate, ::Mt4TermApi::CustomChartApplyTemplateRequest, ::Mt4TermApi::CustomChartApplyTemplateReply
    end

    Stub = Service.rpc_stub_class
  end
end
