# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mt4-term-api-trading-helper.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
require 'google/api/annotations_pb'
require 'mrpc-mt4-error_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("mt4-term-api-trading-helper.proto", :syntax => :proto3) do
    add_message "mt4_term_api.OrderCloseByRequest" do
      optional :ticket_to_close, :int32, 1
      optional :opposite_ticket_closing_by, :int32, 2
    end
    add_message "mt4_term_api.OrderCloseByReply" do
      oneof :response do
        optional :data, :message, 1, "mt4_term_api.OrderCloseByData"
        optional :error, :message, 2, "mt4_term_api.Error"
      end
    end
    add_message "mt4_term_api.OrderCloseByData" do
      optional :close_price, :double, 1
      optional :profit, :double, 2
      optional :close_time, :message, 3, "google.protobuf.Timestamp"
    end
    add_message "mt4_term_api.OrderSendRequest" do
      optional :symbol, :string, 1
      optional :operation_type, :enum, 2, "mt4_term_api.OrderSendOperationType"
      optional :volume, :double, 3
      proto3_optional :price, :double, 4
      proto3_optional :slippage, :int32, 5
      proto3_optional :stoploss, :double, 6
      proto3_optional :takeprofit, :double, 7
      proto3_optional :comment, :string, 8
      proto3_optional :magic_number, :int32, 9
      proto3_optional :expiration, :message, 10, "google.protobuf.Timestamp"
    end
    add_message "mt4_term_api.OrderSendReply" do
      oneof :response do
        optional :data, :message, 1, "mt4_term_api.OrderSendData"
        optional :error, :message, 2, "mt4_term_api.Error"
      end
    end
    add_message "mt4_term_api.OrderSendData" do
      optional :ticket, :int32, 1
      optional :volume, :double, 2
      optional :price, :double, 3
      optional :open_time, :message, 4, "google.protobuf.Timestamp"
    end
    add_message "mt4_term_api.OrderModifyRequest" do
      optional :order_ticket, :int32, 1
      proto3_optional :new_price, :double, 2
      proto3_optional :new_stop_loss, :double, 3
      proto3_optional :new_take_profit, :double, 4
      proto3_optional :new_expiration, :message, 5, "google.protobuf.Timestamp"
    end
    add_message "mt4_term_api.OrderModifyReply" do
      oneof :response do
        optional :data, :message, 1, "mt4_term_api.OrderModifyData"
        optional :error, :message, 2, "mt4_term_api.Error"
      end
    end
    add_message "mt4_term_api.OrderModifyData" do
      optional :order_was_modified, :bool, 1
    end
    add_message "mt4_term_api.OrderCloseDeleteRequest" do
      optional :order_ticket, :int32, 1
      proto3_optional :lots, :double, 2
      proto3_optional :closing_price, :double, 3
      proto3_optional :slippage, :int32, 4
    end
    add_message "mt4_term_api.OrderCloseDeleteReply" do
      oneof :response do
        optional :data, :message, 1, "mt4_term_api.OrderCloseDeleteData"
        optional :error, :message, 2, "mt4_term_api.Error"
      end
    end
    add_message "mt4_term_api.OrderCloseDeleteData" do
      optional :mode, :enum, 1, "mt4_term_api.OrderCloseDeleteMode"
      proto3_optional :history_order_comment, :string, 2
    end
    add_enum "mt4_term_api.OrderSendOperationType" do
      value :OC_OP_BUY, 0
      value :OC_OP_SELL, 1
      value :OC_OP_BUYLIMIT, 2
      value :OC_OP_SELLLIMIT, 3
      value :OC_OP_BUYSTOP, 4
      value :OC_OP_SELLSTOP, 5
    end
    add_enum "mt4_term_api.OrderCloseDeleteMode" do
      value :OCD_MARKET_ORDER, 0
      value :OCD_PENDING_ORDER, 1
    end
  end
end

module Mt4TermApi
  OrderCloseByRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.OrderCloseByRequest").msgclass
  OrderCloseByReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.OrderCloseByReply").msgclass
  OrderCloseByData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.OrderCloseByData").msgclass
  OrderSendRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.OrderSendRequest").msgclass
  OrderSendReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.OrderSendReply").msgclass
  OrderSendData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.OrderSendData").msgclass
  OrderModifyRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.OrderModifyRequest").msgclass
  OrderModifyReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.OrderModifyReply").msgclass
  OrderModifyData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.OrderModifyData").msgclass
  OrderCloseDeleteRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.OrderCloseDeleteRequest").msgclass
  OrderCloseDeleteReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.OrderCloseDeleteReply").msgclass
  OrderCloseDeleteData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.OrderCloseDeleteData").msgclass
  OrderSendOperationType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.OrderSendOperationType").enummodule
  OrderCloseDeleteMode = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.OrderCloseDeleteMode").enummodule
end
