# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: mt4-term-api-subscriptions.proto for package 'mt4_term_api'

require 'grpc'
require 'mt4-term-api-subscriptions_pb'

module Mt4TermApi
  module SubscriptionService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'mt4_term_api.SubscriptionService'

      # Streams real-time order/trade events.
      # Requires 'id' header — use GetId to generate.
      # Swagger does not support streaming — use /subscription-stream interactive viewer.
      rpc :OnTrade, ::Mt4TermApi::OnTradeRequest, stream(::Mt4TermApi::OnTradeReply)
      # Streams the tickets of currently opened orders as they change.
      # Requires 'id' header — use GetId to generate.
      # Swagger does not support streaming — use /subscription-stream interactive viewer.
      rpc :OnOpenedOrdersTickets, ::Mt4TermApi::OnOpenedOrdersTicketsRequest, stream(::Mt4TermApi::OnOpenedOrdersTicketsReply)
      # Streams the live profit of currently opened orders.
      # Requires 'id' header — use GetId to generate.
      # Swagger does not support streaming — use /subscription-stream interactive viewer.
      rpc :OnOpenedOrdersProfit, ::Mt4TermApi::OnOpenedOrdersProfitRequest, stream(::Mt4TermApi::OnOpenedOrdersProfitReply)
      # Streams real-time ticks for the given symbols.
      # Requires 'id' header — use GetId to generate.
      # Swagger does not support streaming — use /subscription-stream interactive viewer.
      # [DefaultValues]
      # {
      #   "symbolNames": "EURUSD,BTCUSD"
      # }
      rpc :OnSymbolTick, ::Mt4TermApi::OnSymbolTickRequest, stream(::Mt4TermApi::OnSymbolTickReply)
    end

    Stub = Service.rpc_stub_class
  end
end
