# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: mt4-term-api-charts.proto for package 'mt4_term_api'

require 'grpc'
require 'mt4-term-api-charts_pb'

module Mt4TermApi
  module Charts
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'mt4_term_api.Charts'

      rpc :GetEaParams, ::Mt4TermApi::GetEaParamsRequest, ::Mt4TermApi::GetEaParamsReply
      rpc :OpenTerminalChartWithEa, ::Mt4TermApi::OpenTerminalChartWithEaRequest, ::Mt4TermApi::OpenTerminalChartWithEaReply
      rpc :AttachEa, ::Mt4TermApi::AttachEaRequest, ::Mt4TermApi::AttachEaReply
      rpc :GetRunningEas, ::Mt4TermApi::GetRunningEasRequest, ::Mt4TermApi::GetRunningEasReply
      rpc :GetEaLogs, ::Mt4TermApi::GetEaLogsRequest, ::Mt4TermApi::GetEaLogsReply
      rpc :StopEa, ::Mt4TermApi::StopEaRequest, ::Mt4TermApi::StopEaReply
    end

    Stub = Service.rpc_stub_class
  end
end
