# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mt4-term-api-health-check.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("mt4-term-api-health-check.proto", :syntax => :proto3) do
    add_message "mt4_term_api.HealthCheckRequest" do
    end
    add_message "mt4_term_api.HealthCheckReply" do
      optional :connected, :bool, 1
      optional :serverTimeMsc, :int64, 2
    end
    add_message "mt4_term_api.CloseTerminalRequest" do
    end
    add_message "mt4_term_api.CloseTerminalReply" do
    end
  end
end

module Mt4TermApi
  HealthCheckRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.HealthCheckRequest").msgclass
  HealthCheckReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.HealthCheckReply").msgclass
  CloseTerminalRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.CloseTerminalRequest").msgclass
  CloseTerminalReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.CloseTerminalReply").msgclass
end
