# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mt4-term-api-subscriptions.proto

require 'google/protobuf'

require 'google/api/annotations_pb'
require 'google/protobuf/timestamp_pb'
require 'mrpc-mt4-error_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("mt4-term-api-subscriptions.proto", :syntax => :proto3) do
    add_message "mt4_term_api.OnSymbolTickRequest" do
      repeated :symbol_names, :string, 1
    end
    add_message "mt4_term_api.OnSymbolTickReply" do
      oneof :response do
        optional :data, :message, 1, "mt4_term_api.OnSymbolTickData"
        optional :error, :message, 2, "mt4_term_api.Error"
      end
    end
    add_message "mt4_term_api.OnSymbolTickData" do
      optional :symbol_tick, :message, 1, "mt4_term_api.OnSymbolMqlTickInfo"
      optional :terminal_instance_guid_id, :string, 2
    end
    add_message "mt4_term_api.OnSymbolMqlTickInfo" do
      optional :time, :message, 1, "google.protobuf.Timestamp"
      optional :bid, :double, 2
      optional :ask, :double, 3
      optional :last, :double, 4
      optional :volume, :uint64, 5
      optional :time_msc, :int64, 6
      optional :symbol, :string, 7
    end
    add_message "mt4_term_api.OnTradeRequest" do
    end
    add_message "mt4_term_api.OnTradeReply" do
      oneof :response do
        optional :data, :message, 1, "mt4_term_api.OnTradeData"
        optional :error, :message, 2, "mt4_term_api.Error"
      end
    end
    add_message "mt4_term_api.OnTradeData" do
      optional :type, :enum, 1, "mt4_term_api.MT4_SUB_ENUM_EVENT_GROUP_TYPE"
      optional :event_data, :message, 2, "mt4_term_api.OnTadeEventData"
      optional :account_info, :message, 3, "mt4_term_api.OnEventAccountInfo"
      optional :terminal_instance_guid_id, :string, 4
    end
    add_message "mt4_term_api.OnTadeEventData" do
      repeated :new_orders, :message, 1, "mt4_term_api.OnTradeOrderInfo"
      repeated :updated_orders, :message, 2, "mt4_term_api.OnTradeUpdatedOrderInfo"
      repeated :removed_orders, :message, 3, "mt4_term_api.OnTradeOrderInfo"
      repeated :new_history_orders, :message, 4, "mt4_term_api.OnTradeOrderInfo"
    end
    add_message "mt4_term_api.OnTradeOrderInfo" do
      optional :index, :int32, 1
      optional :ticket, :int32, 2
      optional :is_history, :bool, 3
      optional :comment, :string, 4
      optional :commission, :double, 5
      optional :expiration, :message, 6, "google.protobuf.Timestamp"
      optional :lots, :double, 7
      optional :magic_number, :int32, 8
      optional :open_price, :double, 9
      optional :open_time, :message, 10, "google.protobuf.Timestamp"
      optional :order_profit, :double, 11
      optional :stop_loss, :double, 12
      optional :swap, :double, 13
      optional :symbol, :string, 14
      optional :take_profit, :double, 15
      optional :type, :enum, 16, "mt4_term_api.SUB_ORDER_OPERATION_TYPE"
      optional :close_price, :double, 17
      optional :close_time, :message, 18, "google.protobuf.Timestamp"
      optional :account_login, :int64, 19
    end
    add_message "mt4_term_api.OnTradeUpdatedOrderInfo" do
      optional :previous, :message, 1, "mt4_term_api.OnTradeOrderInfo"
      optional :current, :message, 2, "mt4_term_api.OnTradeOrderInfo"
    end
    add_message "mt4_term_api.OnOpenedOrdersTicketsRequest" do
      optional :pull_interval_milliseconds, :int32, 1
    end
    add_message "mt4_term_api.OnOpenedOrdersTicketsReply" do
      oneof :response do
        optional :data, :message, 1, "mt4_term_api.OnOpenedOrdersTicketsData"
        optional :error, :message, 2, "mt4_term_api.Error"
      end
    end
    add_message "mt4_term_api.OnOpenedOrdersTicketsData" do
      repeated :position_tickets, :int32, 1
      repeated :pending_order_tickets, :int32, 2
      optional :server_time, :message, 3, "google.protobuf.Timestamp"
      optional :terminal_instance_guid_id, :string, 5
    end
    add_message "mt4_term_api.OnOpenedOrdersProfitRequest" do
      optional :timer_period_milliseconds, :int32, 1
    end
    add_message "mt4_term_api.OnOpenedOrdersProfitReply" do
      oneof :response do
        optional :data, :message, 1, "mt4_term_api.OnOpenedOrdersProfitData"
        optional :error, :message, 2, "mt4_term_api.Error"
      end
    end
    add_message "mt4_term_api.OnOpenedOrdersProfitData" do
      optional :type, :enum, 1, "mt4_term_api.MT4_SUB_ENUM_EVENT_GROUP_TYPE"
      repeated :opened_orders_with_profit_updated, :message, 2, "mt4_term_api.OnOpenedOrdersProfitOrderInfo"
      optional :account_info, :message, 3, "mt4_term_api.OnEventAccountInfo"
      optional :terminal_instance_guid_id, :string, 4
    end
    add_message "mt4_term_api.OnEventAccountInfo" do
      optional :balance, :double, 1
      optional :credit, :double, 2
      optional :equity, :double, 3
      optional :margin, :double, 4
      optional :free_margin, :double, 5
      optional :profit, :double, 6
      optional :margin_level, :double, 7
      optional :login, :int64, 8
    end
    add_message "mt4_term_api.OnOpenedOrdersProfitOrderInfo" do
      optional :index, :int32, 1
      optional :ticket, :int32, 2
      optional :comment, :string, 3
      optional :commission, :double, 4
      optional :expiration, :message, 5, "google.protobuf.Timestamp"
      optional :lots, :double, 6
      optional :magic_number, :int32, 7
      optional :open_price, :double, 8
      optional :open_time, :message, 9, "google.protobuf.Timestamp"
      optional :order_profit, :double, 10
      optional :stop_loss, :double, 11
      optional :swap, :double, 12
      optional :symbol, :string, 13
      optional :take_profit, :double, 14
      optional :type, :enum, 15, "mt4_term_api.SUB_ORDER_OPERATION_TYPE"
    end
    add_enum "mt4_term_api.SUB_ORDER_OPERATION_TYPE" do
      value :SUB_OP_BUY, 0
      value :SUB_OP_SELL, 1
      value :SUB_OP_BUYLIMIT, 2
      value :SUB_OP_SELLLIMIT, 3
      value :SUB_OP_BUYSTOP, 4
      value :SUB_OP_SELLSTOP, 5
    end
    add_enum "mt4_term_api.MT4_SUB_ENUM_EVENT_GROUP_TYPE" do
      value :OrderProfit, 0
      value :OrderUpdate, 1
    end
  end
end

module Mt4TermApi
  OnSymbolTickRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.OnSymbolTickRequest").msgclass
  OnSymbolTickReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.OnSymbolTickReply").msgclass
  OnSymbolTickData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.OnSymbolTickData").msgclass
  OnSymbolMqlTickInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.OnSymbolMqlTickInfo").msgclass
  OnTradeRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.OnTradeRequest").msgclass
  OnTradeReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.OnTradeReply").msgclass
  OnTradeData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.OnTradeData").msgclass
  OnTadeEventData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.OnTadeEventData").msgclass
  OnTradeOrderInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.OnTradeOrderInfo").msgclass
  OnTradeUpdatedOrderInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.OnTradeUpdatedOrderInfo").msgclass
  OnOpenedOrdersTicketsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.OnOpenedOrdersTicketsRequest").msgclass
  OnOpenedOrdersTicketsReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.OnOpenedOrdersTicketsReply").msgclass
  OnOpenedOrdersTicketsData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.OnOpenedOrdersTicketsData").msgclass
  OnOpenedOrdersProfitRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.OnOpenedOrdersProfitRequest").msgclass
  OnOpenedOrdersProfitReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.OnOpenedOrdersProfitReply").msgclass
  OnOpenedOrdersProfitData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.OnOpenedOrdersProfitData").msgclass
  OnEventAccountInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.OnEventAccountInfo").msgclass
  OnOpenedOrdersProfitOrderInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.OnOpenedOrdersProfitOrderInfo").msgclass
  SUB_ORDER_OPERATION_TYPE = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.SUB_ORDER_OPERATION_TYPE").enummodule
  MT4_SUB_ENUM_EVENT_GROUP_TYPE = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.MT4_SUB_ENUM_EVENT_GROUP_TYPE").enummodule
end
