# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: mt4-term-api-demo-account.proto for package 'mt4_term_api'

require 'grpc'
require 'mt4-term-api-demo-account_pb'

module Mt4TermApi
  module DemoAccount
    # Demo account creation service. Automates the MT4 "Open an Account" wizard via
    # Win32 GUI automation (proxied to the terminal's Gui service).
    # Does NOT require 'id' header — auto-picks any available terminal.
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'mt4_term_api.DemoAccount'

      # Search for broker companies by name (reads the wizard's broker ListView).
      # [DefaultValues]
      # { "searchText": "MetaQuotes" }
      rpc :FindCompanies, ::Mt4TermApi::GuiDemoFindCompaniesRequest, ::Mt4TermApi::GuiDemoFindCompaniesReply
      # Get available servers and account types for a company.
      # [DefaultValues]
      # { "companyName": "MetaQuotes Ltd." }
      rpc :ServersAndAccountTypes, ::Mt4TermApi::GuiDemoServersAndTypesRequest, ::Mt4TermApi::GuiDemoServersAndTypesReply
      # Open a demo account. Full wizard flow: search -> select -> fill form -> register.
      # [DefaultValues]
      # { "company": "MetaQuotes Ltd.", "firstName": "Test", "lastName": "User",
      #   "email": "test@test.com", "phone": "+1234567890", "timeoutSeconds": "60" }
      rpc :OpenDemoAccount, ::Mt4TermApi::GuiDemoOpenAccountRequest, ::Mt4TermApi::GuiDemoOpenAccountReply
      # Same as OpenDemoAccount but streams real-time progress events.
      # Swagger does not support streaming — use /demo-account-stream interactive viewer.
      rpc :OpenDemoAccountStream, ::Mt4TermApi::GuiDemoOpenAccountRequest, stream(::Mt4TermApi::DemoAccountStreamEvent)
    end

    Stub = Service.rpc_stub_class
  end
end
