# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mt4-term-api-internal-charts.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("mt4-term-api-internal-charts.proto", :syntax => :proto3) do
    add_message "mt4_term_api.CustomChartApplyTemplateReply" do
    end
    add_message "mt4_term_api.CustomChartApplyTemplateRequest" do
      optional :chart_id, :int64, 1
      optional :template_file_name, :string, 2
    end
    add_message "mt4_term_api.CustomChartSaveTemplateRequest" do
      optional :chart_id, :int64, 1
    end
    add_message "mt4_term_api.CustomChartSaveTemplateReply" do
      optional :template_file_name, :string, 1
    end
    add_message "mt4_term_api.CustomChartOpenRequest" do
      optional :chart_symbol, :string, 1
      optional :chart_period_int, :int32, 2
    end
    add_message "mt4_term_api.CustomChartOpenReply" do
      optional :chart_id, :int64, 1
    end
    add_message "mt4_term_api.ChartOpenRequest" do
      optional :chart_symbol, :string, 1
      optional :mode, :enum, 2, "mt4_term_api.ChartTemplateMode"
    end
    add_message "mt4_term_api.ChartOpenReply" do
      optional :chart_terminal_id, :int64, 1
    end
    add_message "mt4_term_api.ChartCloseRequest" do
      optional :chart_terminal_id, :int64, 1
    end
    add_message "mt4_term_api.ChartCloseReply" do
    end
    add_enum "mt4_term_api.ChartTemplateMode" do
      value :ON_TRADE, 0
      value :ON_OPENED_ORDERS_TICKETS, 1
      value :ON_ORDER_PROFIT, 2
      value :ON_SYMBOL_INFO_TICK, 3
    end
  end
end

module Mt4TermApi
  CustomChartApplyTemplateReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.CustomChartApplyTemplateReply").msgclass
  CustomChartApplyTemplateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.CustomChartApplyTemplateRequest").msgclass
  CustomChartSaveTemplateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.CustomChartSaveTemplateRequest").msgclass
  CustomChartSaveTemplateReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.CustomChartSaveTemplateReply").msgclass
  CustomChartOpenRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.CustomChartOpenRequest").msgclass
  CustomChartOpenReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.CustomChartOpenReply").msgclass
  ChartOpenRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.ChartOpenRequest").msgclass
  ChartOpenReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.ChartOpenReply").msgclass
  ChartCloseRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.ChartCloseRequest").msgclass
  ChartCloseReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.ChartCloseReply").msgclass
  ChartTemplateMode = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.ChartTemplateMode").enummodule
end
