# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mt4-term-api-market-info.proto

require 'google/protobuf'

require 'google/api/annotations_pb'
require 'google/protobuf/timestamp_pb'
require 'mrpc-mt4-error_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("mt4-term-api-market-info.proto", :syntax => :proto3) do
    add_message "mt4_term_api.QuoteRequest" do
      optional :symbol, :string, 1
    end
    add_message "mt4_term_api.QuoteReply" do
      oneof :response do
        optional :data, :message, 1, "mt4_term_api.QuoteData"
        optional :error, :message, 2, "mt4_term_api.Error"
      end
    end
    add_message "mt4_term_api.QuoteData" do
      optional :symbol, :string, 1
      optional :bid, :double, 2
      optional :ask, :double, 3
      optional :date_time, :message, 4, "google.protobuf.Timestamp"
      optional :high, :double, 5
      optional :low, :double, 6
    end
    add_message "mt4_term_api.QuoteManyRequest" do
      repeated :symbols, :string, 1
    end
    add_message "mt4_term_api.QuoteManyReply" do
      oneof :response do
        optional :data, :message, 1, "mt4_term_api.QuoteManyData"
        optional :error, :message, 2, "mt4_term_api.Error"
      end
    end
    add_message "mt4_term_api.QuoteManyData" do
      repeated :quotes, :message, 1, "mt4_term_api.QuoteData"
    end
    add_message "mt4_term_api.SymbolsRequest" do
    end
    add_message "mt4_term_api.SymbolsReply" do
      oneof :response do
        optional :data, :message, 1, "mt4_term_api.SymbolsData"
        optional :error, :message, 2, "mt4_term_api.Error"
      end
    end
    add_message "mt4_term_api.SymbolsData" do
      repeated :SymbolNameInfos, :message, 1, "mt4_term_api.SymbolNameInfo"
    end
    add_message "mt4_term_api.SymbolNameInfo" do
      optional :symbol_name, :string, 1
      optional :symbol_index, :int32, 2
    end
    add_message "mt4_term_api.QuoteHistoryRequest" do
      optional :symbol, :string, 1
      optional :timeframe, :enum, 2, "mt4_term_api.ENUM_QUOTE_HISTORY_TIMEFRAME"
      optional :fromTime, :message, 3, "google.protobuf.Timestamp"
      optional :toTime, :message, 4, "google.protobuf.Timestamp"
    end
    add_message "mt4_term_api.QuoteHistoryReply" do
      oneof :response do
        optional :data, :message, 1, "mt4_term_api.QuoteHistoryData"
        optional :error, :message, 2, "mt4_term_api.Error"
      end
    end
    add_message "mt4_term_api.QuoteHistoryData" do
      repeated :historical_quotes, :message, 1, "mt4_term_api.HistoryQuote"
    end
    add_message "mt4_term_api.HistoryQuote" do
      optional :symbol, :string, 1
      optional :index, :int32, 2
      optional :time, :message, 3, "google.protobuf.Timestamp"
      optional :open, :double, 4
      optional :close, :double, 5
      optional :high, :double, 6
      optional :low, :double, 7
      optional :real_volume, :int64, 8
      optional :tick_volume, :int64, 9
      optional :spread, :int32, 10
    end
    add_message "mt4_term_api.SymbolSelectRequest" do
      optional :symbol, :string, 1
      optional :select, :bool, 2
    end
    add_message "mt4_term_api.SymbolSelectReply" do
      oneof :response do
        optional :data, :message, 1, "mt4_term_api.SymbolSelectData"
        optional :error, :message, 2, "mt4_term_api.Error"
      end
    end
    add_message "mt4_term_api.SymbolSelectData" do
      optional :success, :bool, 1
    end
    add_enum "mt4_term_api.ENUM_QUOTE_HISTORY_TIMEFRAME" do
      value :QH_PERIOD_M1, 0
      value :QH_PERIOD_M5, 1
      value :QH_PERIOD_M15, 2
      value :QH_PERIOD_M30, 3
      value :QH_PERIOD_H1, 4
      value :QH_PERIOD_H4, 5
      value :QH_PERIOD_D1, 6
      value :QH_PERIOD_W1, 7
      value :QH_PERIOD_MN1, 8
    end
  end
end

module Mt4TermApi
  QuoteRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.QuoteRequest").msgclass
  QuoteReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.QuoteReply").msgclass
  QuoteData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.QuoteData").msgclass
  QuoteManyRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.QuoteManyRequest").msgclass
  QuoteManyReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.QuoteManyReply").msgclass
  QuoteManyData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.QuoteManyData").msgclass
  SymbolsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.SymbolsRequest").msgclass
  SymbolsReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.SymbolsReply").msgclass
  SymbolsData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.SymbolsData").msgclass
  SymbolNameInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.SymbolNameInfo").msgclass
  QuoteHistoryRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.QuoteHistoryRequest").msgclass
  QuoteHistoryReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.QuoteHistoryReply").msgclass
  QuoteHistoryData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.QuoteHistoryData").msgclass
  HistoryQuote = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.HistoryQuote").msgclass
  SymbolSelectRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.SymbolSelectRequest").msgclass
  SymbolSelectReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.SymbolSelectReply").msgclass
  SymbolSelectData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.SymbolSelectData").msgclass
  ENUM_QUOTE_HISTORY_TIMEFRAME = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.ENUM_QUOTE_HISTORY_TIMEFRAME").enummodule
end
