# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: mt4-term-api-market-info.proto for package 'mt4_term_api'

require 'grpc'
require 'mt4-term-api-market-info_pb'

module Mt4TermApi
  module MarketInfo
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'mt4_term_api.MarketInfo'

      # Get quote
      rpc :Quote, ::Mt4TermApi::QuoteRequest, ::Mt4TermApi::QuoteReply
      # Latest quote for the specified symbol
      rpc :QuoteMany, ::Mt4TermApi::QuoteManyRequest, ::Mt4TermApi::QuoteManyReply
      rpc :Symbols, ::Mt4TermApi::SymbolsRequest, ::Mt4TermApi::SymbolsReply
      rpc :QuoteHistory, ::Mt4TermApi::QuoteHistoryRequest, ::Mt4TermApi::QuoteHistoryReply
      # Selects a symbol in the Market Watch window or removes a symbol from the window
      # https://docs.mql4.com/marketinformation/symbolselect
      rpc :SymbolSelect, ::Mt4TermApi::SymbolSelectRequest, ::Mt4TermApi::SymbolSelectReply
    end

    Stub = Service.rpc_stub_class
  end
end
