# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mt4-term-api-demo-account.proto

require 'google/protobuf'

require 'google/api/annotations_pb'
require 'mt4-term-api-gui_pb'
require 'google/protobuf/timestamp_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("mt4-term-api-demo-account.proto", :syntax => :proto3) do
    add_message "mt4_term_api.DemoAccountStreamEvent" do
      optional :step, :string, 1
      optional :message, :string, 2
      optional :level, :string, 3
      optional :elapsed_ms, :int64, 4
      optional :timestamp, :message, 5, "google.protobuf.Timestamp"
      optional :is_final, :bool, 6
      optional :account_data, :message, 7, "mt4_term_api.GuiDemoOpenAccountReply"
    end
  end
end

module Mt4TermApi
  DemoAccountStreamEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.DemoAccountStreamEvent").msgclass
end
