# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: mt4-term-api-trading-helper.proto for package 'mt4_term_api'

require 'grpc'
require 'mt4-term-api-trading-helper_pb'

module Mt4TermApi
  module TradingHelper
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'mt4_term_api.TradingHelper'

      # Send market or pending order
      rpc :OrderSend, ::Mt4TermApi::OrderSendRequest, ::Mt4TermApi::OrderSendReply
      # Modify market or pending order
      rpc :OrderModify, ::Mt4TermApi::OrderModifyRequest, ::Mt4TermApi::OrderModifyReply
      # Close market or pending order
      rpc :OrderCloseDelete, ::Mt4TermApi::OrderCloseDeleteRequest, ::Mt4TermApi::OrderCloseDeleteReply
      # Close market order with opposite market order
      rpc :OrderCloseBy, ::Mt4TermApi::OrderCloseByRequest, ::Mt4TermApi::OrderCloseByReply
    end

    Stub = Service.rpc_stub_class
  end
end
