# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mt4-term-api-demo-account.proto

require 'google/protobuf'

require 'google/api/annotations_pb'
require 'mt4-term-api-gui_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("mt4-term-api-demo-account.proto", :syntax => :proto3) do
  end
end

module Mt4TermApi
end
