# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mt4-term-api-gui.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("mt4-term-api-gui.proto", :syntax => :proto3) do
    add_message "mt4_term_api.GuiDemoFindCompaniesRequest" do
      optional :search_text, :string, 1
      optional :timeout_seconds, :int32, 2
    end
    add_message "mt4_term_api.GuiDemoFindCompaniesReply" do
      optional :result_code, :int32, 1
      repeated :companies, :message, 2, "mt4_term_api.GuiDemoCompany"
      optional :debug_log, :string, 3
    end
    add_message "mt4_term_api.GuiDemoCompany" do
      optional :name, :string, 1
      optional :short_name, :string, 2
    end
    add_message "mt4_term_api.GuiDemoServersAndTypesRequest" do
      optional :company_name, :string, 1
      optional :timeout_seconds, :int32, 2
    end
    add_message "mt4_term_api.GuiDemoServersAndTypesReply" do
      optional :result_code, :int32, 1
      repeated :servers, :string, 2
      repeated :account_types, :string, 3
      repeated :deposits, :string, 4
      repeated :leverages, :string, 5
      optional :debug_log, :string, 6
    end
    add_message "mt4_term_api.GuiDemoOpenAccountRequest" do
      optional :company, :string, 1
      optional :first_name, :string, 2
      optional :last_name, :string, 3
      optional :email, :string, 4
      optional :phone, :string, 5
      optional :server, :string, 6
      optional :account_type, :string, 7
      optional :timeout_seconds, :int32, 8
    end
    add_message "mt4_term_api.GuiDemoOpenAccountReply" do
      optional :result_code, :int32, 1
      optional :login, :string, 2
      optional :password, :string, 3
      optional :investor, :string, 4
      optional :server, :string, 5
      optional :debug_log, :string, 6
    end
    add_message "mt4_term_api.GuiDemoProgressEvent" do
      optional :step, :string, 1
      optional :message, :string, 2
      optional :elapsed_ms, :int64, 3
      optional :is_final, :bool, 4
      optional :account_data, :message, 5, "mt4_term_api.GuiDemoOpenAccountReply"
      optional :error_code, :int32, 6
    end
  end
end

module Mt4TermApi
  GuiDemoFindCompaniesRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.GuiDemoFindCompaniesRequest").msgclass
  GuiDemoFindCompaniesReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.GuiDemoFindCompaniesReply").msgclass
  GuiDemoCompany = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.GuiDemoCompany").msgclass
  GuiDemoServersAndTypesRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.GuiDemoServersAndTypesRequest").msgclass
  GuiDemoServersAndTypesReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.GuiDemoServersAndTypesReply").msgclass
  GuiDemoOpenAccountRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.GuiDemoOpenAccountRequest").msgclass
  GuiDemoOpenAccountReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.GuiDemoOpenAccountReply").msgclass
  GuiDemoProgressEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.GuiDemoProgressEvent").msgclass
end
