# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: mt4-term-api-gui.proto for package 'mt4_term_api'

require 'grpc'
require 'mt4-term-api-gui_pb'

module Mt4TermApi
  module Gui
    # Terminal-side GUI-automation service (implemented by mt4-framework-grpc, which
    # P/Invokes mt4-term-gui.dll). The manager's DemoAccount service proxies to these.
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'mt4_term_api.Gui'

      rpc :DemoFindCompanies, ::Mt4TermApi::GuiDemoFindCompaniesRequest, ::Mt4TermApi::GuiDemoFindCompaniesReply
      rpc :DemoServersAndTypes, ::Mt4TermApi::GuiDemoServersAndTypesRequest, ::Mt4TermApi::GuiDemoServersAndTypesReply
      rpc :DemoOpenAccount, ::Mt4TermApi::GuiDemoOpenAccountRequest, ::Mt4TermApi::GuiDemoOpenAccountReply
      rpc :DemoOpenAccountWithProgress, ::Mt4TermApi::GuiDemoOpenAccountRequest, stream(::Mt4TermApi::GuiDemoProgressEvent)
    end

    Stub = Service.rpc_stub_class
  end
end
