# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mt4-term-api-account-helper.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
require 'google/api/annotations_pb'
require 'mrpc-mt4-error_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("mt4-term-api-account-helper.proto", :syntax => :proto3) do
    add_message "mt4_term_api.AccountSummaryRequest" do
    end
    add_message "mt4_term_api.AccountSummaryReply" do
      oneof :response do
        optional :data, :message, 1, "mt4_term_api.AccountSummaryData"
        optional :error, :message, 2, "mt4_term_api.Error"
      end
    end
    add_message "mt4_term_api.AccountSummaryData" do
      optional :account_login, :int64, 1
      optional :account_balance, :double, 2
      optional :account_equity, :double, 3
      optional :account_user_name, :string, 4
      optional :account_leverage, :int64, 5
      optional :account_trade_mode, :enum, 6, "mt4_term_api.EnumAccountTradeMode"
      optional :account_company_name, :string, 7
      optional :account_currency, :string, 8
      optional :server_time, :message, 9, "google.protobuf.Timestamp"
      optional :account_credit, :double, 10
      optional :is_investor, :bool, 11
      optional :utc_server_time_shift_minutes, :int32, 12
    end
    add_message "mt4_term_api.OpenedOrdersRequest" do
      optional :sort_type, :enum, 1, "mt4_term_api.EnumOpenedOrderSortType"
    end
    add_message "mt4_term_api.OpenedOrdersReply" do
      oneof :response do
        optional :data, :message, 1, "mt4_term_api.OpenedOrdersData"
        optional :error, :message, 2, "mt4_term_api.Error"
      end
    end
    add_message "mt4_term_api.OpenedOrdersData" do
      repeated :order_infos, :message, 1, "mt4_term_api.OpenedOrderInfo"
    end
    add_message "mt4_term_api.OpenedOrderInfo" do
      optional :comment, :string, 1
      optional :commision, :double, 2
      optional :expiration_time, :message, 3, "google.protobuf.Timestamp"
      optional :lots, :double, 4
      optional :magic_number, :int32, 5
      optional :open_price, :double, 6
      optional :profit, :double, 7
      optional :stop_loss, :double, 8
      optional :swap, :double, 9
      optional :symbol, :string, 10
      optional :take_profit, :double, 11
      optional :ticket, :int32, 12
      optional :position_index, :int32, 13
      optional :order_type, :enum, 14, "mt4_term_api.OpenedOrderType"
      optional :sort_index, :int32, 15
      optional :open_time, :message, 16, "google.protobuf.Timestamp"
      optional :account_login, :int64, 17
    end
    add_message "mt4_term_api.OpenedOrdersTicketsRequest" do
    end
    add_message "mt4_term_api.OpenedOrdersTicketsReply" do
      oneof :response do
        optional :data, :message, 1, "mt4_term_api.OpenedOrdersTicketsData"
        optional :error, :message, 2, "mt4_term_api.Error"
      end
    end
    add_message "mt4_term_api.OpenedOrdersTicketsData" do
      repeated :tickets, :int32, 1
    end
    add_message "mt4_term_api.OrdersHistoryReply" do
      oneof :response do
        optional :data, :message, 1, "mt4_term_api.OrdersHistoryData"
        optional :error, :message, 2, "mt4_term_api.Error"
      end
    end
    add_message "mt4_term_api.OrdersHistoryData" do
      repeated :orders_info, :message, 1, "mt4_term_api.HistoryOrderInfo"
      optional :total_count, :int32, 2
    end
    add_message "mt4_term_api.HistoryOrderInfo" do
      optional :comment, :string, 1
      optional :commision, :double, 2
      optional :expiration_time, :message, 3, "google.protobuf.Timestamp"
      optional :lots, :double, 4
      optional :magic_number, :int32, 5
      optional :open_price, :double, 6
      optional :profit, :double, 7
      optional :stop_loss, :double, 8
      optional :swap, :double, 9
      optional :symbol, :string, 10
      optional :take_profit, :double, 11
      optional :ticket, :int32, 12
      optional :position_index, :int32, 13
      optional :order_type, :enum, 14, "mt4_term_api.OpenedOrderType"
      optional :sort_index, :int32, 15
      optional :open_time, :message, 16, "google.protobuf.Timestamp"
      optional :close_time, :message, 17, "google.protobuf.Timestamp"
      optional :close_price, :double, 18
      optional :account_login, :int64, 19
    end
    add_message "mt4_term_api.OrdersHistoryRequest" do
      optional :input_sort_mode, :enum, 1, "mt4_term_api.EnumOrderHistorySortType"
      proto3_optional :input_from, :message, 2, "google.protobuf.Timestamp"
      proto3_optional :input_to, :message, 3, "google.protobuf.Timestamp"
      proto3_optional :page_number, :int32, 4
      proto3_optional :items_per_page, :int32, 5
    end
    add_message "mt4_term_api.SymbolParamsManyRequest" do
      proto3_optional :symbol_name, :string, 1
    end
    add_message "mt4_term_api.SymbolParamsManyReply" do
      oneof :response do
        optional :data, :message, 1, "mt4_term_api.SymbolParamsManyData"
        optional :error, :message, 2, "mt4_term_api.Error"
      end
    end
    add_message "mt4_term_api.SymbolParamsManyData" do
      repeated :symbol_infos, :message, 1, "mt4_term_api.SymbolParamsManyInfo"
    end
    add_message "mt4_term_api.SymbolParamsManyInfo" do
      optional :is_selected, :bool, 1
      optional :visible, :bool, 2
      optional :session_deals, :int64, 3
      optional :session_buy_orders, :int64, 4
      optional :session_sell_orders, :int64, 5
      optional :volume, :int64, 6
      optional :volume_high, :int64, 7
      optional :VolumeLow, :int64, 8
      optional :Time, :int64, 9
      optional :Digits, :int32, 10
      optional :SpreadFloat, :bool, 11
      optional :TicksBookDepth, :int32, 12
      optional :TradeCalcMode, :enum, 13, "mt4_term_api.SP_ENUM_TRADE_CALC_MODE"
      optional :TradeMode, :enum, 14, "mt4_term_api.SP_ENUM_SYMBOL_TRADE_MODE"
      optional :StartTime, :message, 15, "google.protobuf.Timestamp"
      optional :ExpirationTime, :message, 16, "google.protobuf.Timestamp"
      optional :TradeStopsLevel, :int32, 17
      optional :TradeFreezeLevel, :int32, 18
      optional :TradeExeMode, :enum, 19, "mt4_term_api.SP_ENUM_SYMBOL_TRADE_EXECUTION"
      optional :SwapMode, :int32, 20
      optional :SwapRollover3Days, :int32, 21
      optional :TheLast, :double, 22
      optional :LastHigh, :double, 23
      optional :LastLow, :double, 24
      optional :Point, :double, 25
      optional :TradeTickValue, :double, 26
      optional :TradeTickValueProfit, :double, 27
      optional :TradeTickValueLoss, :double, 28
      optional :TradeTickSize, :double, 29
      optional :TradeContractSize, :double, 30
      optional :VolumeMin, :double, 31
      optional :VolumeMax, :double, 32
      optional :VolumeStep, :double, 33
      optional :VolumeLimit, :double, 34
      optional :SwapLong, :double, 35
      optional :SwapShort, :double, 36
      optional :MarginInitial, :double, 37
      optional :MarginMaintenance, :double, 38
      optional :MarginLong, :double, 39
      optional :MarginShort, :double, 40
      optional :MarginLimit, :double, 41
      optional :MarginStop, :double, 42
      optional :MarginStopLimit, :double, 43
      optional :SessionVolume, :double, 44
      optional :SessionTurnover, :double, 45
      optional :SessionInterest, :double, 46
      optional :SessionBuyOrdersVolume, :double, 47
      optional :SessionSellOrdersVolume, :double, 48
      optional :SessionOpen, :double, 49
      optional :SessionClose, :double, 50
      optional :SessionAW, :double, 51
      optional :SessionPriceSettlement, :double, 52
      optional :SessionPriceLimitMin, :double, 53
      optional :SessionPriceLimitMax, :double, 54
      optional :Bid, :double, 55
      optional :BidHigh, :double, 56
      optional :BidLow, :double, 57
      optional :AskHigh, :double, 58
      optional :AskLow, :double, 59
      optional :CurrencyBase, :string, 60
      optional :CurrencyProfit, :string, 61
      optional :CurrencyMargin, :string, 62
      optional :Bank, :string, 63
      optional :SymDescription, :string, 64
      optional :Isin, :string, 65
      optional :Path, :string, 66
      optional :SymbolName, :string, 67
    end
    add_message "mt4_term_api.TickValueWithSizeRequest" do
      repeated :symbol_names, :string, 1
    end
    add_message "mt4_term_api.TickValueWithSizeReply" do
      oneof :response do
        optional :data, :message, 1, "mt4_term_api.TickValueWithSizeData"
        optional :error, :message, 2, "mt4_term_api.Error"
      end
    end
    add_message "mt4_term_api.TickValueWithSizeData" do
      repeated :infos, :message, 1, "mt4_term_api.SymbolTickValueWithSizeInfo"
    end
    add_message "mt4_term_api.SymbolTickValueWithSizeInfo" do
      optional :index, :int32, 1
      optional :symbolName, :string, 2
      optional :TradeTickValue, :double, 3
      optional :TradeTickSize, :double, 4
      optional :TradeContractSize, :double, 5
    end
    add_enum "mt4_term_api.EnumAccountTradeMode" do
      value :ACCOUNT_TRADE_MODE_DEMO, 0
      value :ACCOUNT_TRADE_MODE_CONTEST, 1
      value :ACCOUNT_TRADE_MODE_REAL, 2
    end
    add_enum "mt4_term_api.EnumOpenedOrderSortType" do
      value :SORT_BY_OPEN_TIME_ASC, 0
      value :SORT_BY_OPEN_TIME_DESC, 1
      value :SORT_BY_ORDER_TICKET_ID_ASC, 2
      value :SORT_BY_ORDER_TICKET_ID_DESC, 3
    end
    add_enum "mt4_term_api.OpenedOrderType" do
      value :OO_OP_BUY, 0
      value :OO_OP_SELL, 1
      value :OO_OP_BUYLIMIT, 2
      value :OO_OP_SELLLIMIT, 3
      value :OO_OP_BUYSTOP, 4
      value :OO_OP_SELLSTOP, 5
    end
    add_enum "mt4_term_api.EnumOrderHistorySortType" do
      value :HISTORY_SORT_BY_OPEN_TIME_ASC, 0
      value :HISTORY_SORT_BY_OPEN_TIME_DESC, 1
      value :HISTORY_SORT_BY_CLOSE_TIME_ASC, 2
      value :HISTORY_SORT_BY_CLOSE_TIME_DESC, 3
      value :HISTORY_SORT_BY_ORDER_TICKET_ID_ASC, 4
      value :HISTORY_SORT_BY_ORDER_TICKET_ID_DESC, 5
    end
    add_enum "mt4_term_api.SP_ENUM_SYMBOL_TRADE_MODE" do
      value :SYMBOL_TRADE_MODE_DISABLED, 0
      value :SYMBOL_TRADE_MODE_LONGONLY, 1
      value :SYMBOL_TRADE_MODE_SHORTONLY, 2
      value :SYMBOL_TRADE_MODE_CLOSEONLY, 3
      value :SYMBOL_TRADE_MODE_FULL, 4
    end
    add_enum "mt4_term_api.SP_ENUM_SYMBOL_TRADE_EXECUTION" do
      value :SYMBOL_TRADE_EXECUTION_REQUEST, 0
      value :SYMBOL_TRADE_EXECUTION_INSTANT, 1
      value :SYMBOL_TRADE_EXECUTION_MARKET, 2
      value :SYMBOL_TRADE_EXECUTION_EXCHANGE, 3
    end
    add_enum "mt4_term_api.SP_ENUM_TRADE_CALC_MODE" do
      value :SYMBOL_TRADE_MARGINE_CALC_MODE_FOREX, 0
      value :SYMBOL_TRADE_MARGINE_CALC_MODE_FUTURES, 1
      value :SYMBOL_TRADE_MARGINE_CALC_MODE_CFD, 2
    end
  end
end

module Mt4TermApi
  AccountSummaryRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.AccountSummaryRequest").msgclass
  AccountSummaryReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.AccountSummaryReply").msgclass
  AccountSummaryData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.AccountSummaryData").msgclass
  OpenedOrdersRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.OpenedOrdersRequest").msgclass
  OpenedOrdersReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.OpenedOrdersReply").msgclass
  OpenedOrdersData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.OpenedOrdersData").msgclass
  OpenedOrderInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.OpenedOrderInfo").msgclass
  OpenedOrdersTicketsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.OpenedOrdersTicketsRequest").msgclass
  OpenedOrdersTicketsReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.OpenedOrdersTicketsReply").msgclass
  OpenedOrdersTicketsData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.OpenedOrdersTicketsData").msgclass
  OrdersHistoryReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.OrdersHistoryReply").msgclass
  OrdersHistoryData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.OrdersHistoryData").msgclass
  HistoryOrderInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.HistoryOrderInfo").msgclass
  OrdersHistoryRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.OrdersHistoryRequest").msgclass
  SymbolParamsManyRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.SymbolParamsManyRequest").msgclass
  SymbolParamsManyReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.SymbolParamsManyReply").msgclass
  SymbolParamsManyData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.SymbolParamsManyData").msgclass
  SymbolParamsManyInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.SymbolParamsManyInfo").msgclass
  TickValueWithSizeRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.TickValueWithSizeRequest").msgclass
  TickValueWithSizeReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.TickValueWithSizeReply").msgclass
  TickValueWithSizeData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.TickValueWithSizeData").msgclass
  SymbolTickValueWithSizeInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.SymbolTickValueWithSizeInfo").msgclass
  EnumAccountTradeMode = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.EnumAccountTradeMode").enummodule
  EnumOpenedOrderSortType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.EnumOpenedOrderSortType").enummodule
  OpenedOrderType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.OpenedOrderType").enummodule
  EnumOrderHistorySortType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.EnumOrderHistorySortType").enummodule
  SP_ENUM_SYMBOL_TRADE_MODE = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.SP_ENUM_SYMBOL_TRADE_MODE").enummodule
  SP_ENUM_SYMBOL_TRADE_EXECUTION = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.SP_ENUM_SYMBOL_TRADE_EXECUTION").enummodule
  SP_ENUM_TRADE_CALC_MODE = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("mt4_term_api.SP_ENUM_TRADE_CALC_MODE").enummodule
end
