# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: mt4-term-api-demo-account.proto for package 'mt4_term_api'

require 'grpc'
require 'mt4-term-api-demo-account_pb'

module Mt4TermApi
  module DemoAccount
    # Demo account creation service. Automates the MT4 "Open an Account" wizard via
    # Win32 GUI automation (proxied to the terminal's Gui service).
    # Does NOT require 'id' header — auto-picks any available terminal.
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'mt4_term_api.DemoAccount'

      # Open a demo account. Full wizard flow: search -> select -> fill form -> register.
      # [DefaultValues]
      # { "company": "MetaQuotes Ltd.", "firstName": "Test", "lastName": "User",
      #   "email": "test@test.com", "phone": "+1234567890", "timeoutSeconds": "60" }
      rpc :OpenDemoAccount, ::Mt4TermApi::GuiDemoOpenAccountRequest, ::Mt4TermApi::GuiDemoOpenAccountReply
      # Interactive step-by-step demo account opening wizard.
      # Bidirectional streaming session: search company -> select -> form schema -> submit -> 2FA (if any) -> completed.
      rpc :DemoOpenAccountInteractive, stream(::Mt4TermApi::GuiDemoInteractiveClientMessage), stream(::Mt4TermApi::GuiDemoInteractiveServerMessage)
    end

    Stub = Service.rpc_stub_class
  end
end
