# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: mt4-term-api-account-helper.proto for package 'mt4_term_api'

require 'grpc'
require 'mt4-term-api-account-helper_pb'

module Mt4TermApi
  module AccountHelper
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'mt4_term_api.AccountHelper'

      # Some information about account
      rpc :AccountSummary, ::Mt4TermApi::AccountSummaryRequest, ::Mt4TermApi::AccountSummaryReply
      # List of opened orders
      rpc :OpenedOrders, ::Mt4TermApi::OpenedOrdersRequest, ::Mt4TermApi::OpenedOrdersReply
      # List of opened orders tickets
      rpc :OpenedOrdersTickets, ::Mt4TermApi::OpenedOrdersTicketsRequest, ::Mt4TermApi::OpenedOrdersTicketsReply
      # Orders history with pagination and open date filters
      rpc :OrdersHistory, ::Mt4TermApi::OrdersHistoryRequest, ::Mt4TermApi::OrdersHistoryReply
      # Full information about exact symbol, or all symbols
      rpc :SymbolParamsMany, ::Mt4TermApi::SymbolParamsManyRequest, ::Mt4TermApi::SymbolParamsManyReply
      rpc :TickValueWithSize, ::Mt4TermApi::TickValueWithSizeRequest, ::Mt4TermApi::TickValueWithSizeReply
    end

    Stub = Service.rpc_stub_class
  end
end
