# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: mt4-term-api-connection.proto for package 'mt4_term_api'

require 'grpc'
require 'mt4-term-api-connection_pb'

module Mt4TermApi
  module Connection
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'mt4_term_api.Connection'

      # Creates terminal connection to the MT5 server by MT cluster name, waits for connection and returns Guid of it 
      # [DefaultValues]
      # {
      #   "user": "1124213727",
      #   "password": "1tjvjck",
      #   "mtClusterName": "FreshForex-Demo"
      # }  
      rpc :ConnectEx, ::Mt4TermApi::ConnectExRequest, ::Mt4TermApi::ConnectExReply
      # Creates terminal connection to the MT4 server and returns Guid of it
      # [DefaultValues]
      # {
      #   "user": "501401178",
      #   "password": "v8gctta",
      #   "host": "mt4-demo.roboforex.com",
      #   "port": "443",
      #   "baseChartSymbol": "EURUSD",  
      #   "waitForTerminalIsAlive": "true"
      # }
      rpc :Connect, ::Mt4TermApi::ConnectRequest, ::Mt4TermApi::ConnectReply
      # Connect to account with user, password, host, port.
      # [DefaultValues] 
      # { 
      #  "user": "500476959", 
      #  "password": "ehj4bod", 
      #  "host": "mt4-demo.roboforex.com", 
      #  "port": "443",
      #  "proxyUser": "ProxyUser123", 
      #  "proxyPassword": "qwerty123", 
      #  "proxyHost": "65.108.126.217", 
      #  "proxyPort": "1080", 
      #  "proxyType": "Socks5" 
      # }
      rpc :ConnectProxy, ::Mt4TermApi::ConnectProxyRequest, ::Mt4TermApi::ConnectProxyReply
      # Checks if terminal connection to MT4 server is alive
      rpc :CheckConnect, ::Mt4TermApi::CheckConnectRequest, ::Mt4TermApi::CheckConnectReply
      # Returns detailed live connection state of this terminal instance
      rpc :ConnectState, ::Mt4TermApi::ConnectStateRequest, ::Mt4TermApi::ConnectStateReply
      # Streams real-time connection state changes for specified or visible terminals
      rpc :OnConnectState, ::Mt4TermApi::OnConnectStateRequest, stream(::Mt4TermApi::OnConnectStateReply)
      # Deprecated alias for ConnectState
      rpc :ConnectionStatus, ::Mt4TermApi::ConnectionStatusRequest, ::Mt4TermApi::ConnectionStatusReply
      # Close terminal connection to MT4 server
      rpc :Disconnect, ::Mt4TermApi::DisconnectRequest, ::Mt4TermApi::DisconnectReply
      # If you need to recreate terminal instance with the same id
      rpc :Reconnect, ::Mt4TermApi::ReconnectRequest, ::Mt4TermApi::ReconnectReply
      # Rebuild a terminal instance from a previously-saved token_details_mt4 row. The id header
      # names the terminal to bring back; every credential (User/Password/Server or Host+Port,
      # proxy settings, servers.dat bytes, PfxFile, HardwareId, Build) is read from the DB. Same
      # reply as ConnectEx so callers do not need a separate result path.
      rpc :ConnectByToken, ::Mt4TermApi::ConnectByTokenRequest, ::Mt4TermApi::ConnectExReply
      rpc :GetBrokerServersByBrokerName, ::Mt4TermApi::GetBrokerServersByBrokerNameRequest, ::Mt4TermApi::GetBrokerServersByBrokerNameReply
      # Generates a deterministic GUID from user and password.
      # The same user/password combination always produces the same GUID.
      # Use this GUID as the 'id' header for Connect and other endpoints.
      # [DefaultValues]
      # {
      #   "user": "1124213727",
      #   "password": "1tjvjck"
      # }
      rpc :GetId, ::Mt4TermApi::GetIdRequest, ::Mt4TermApi::GetIdReply
      # Captures a screenshot of the terminal instance window.
      # Handled by Terminal Manager: the per-terminal in-process responder grabs the
      # MT4 window and the manager returns the image. Requires 'id' header.
      rpc :Screenshot, ::Mt4TermApi::ScreenshotRequest, ::Mt4TermApi::ScreenshotReply
      # Same as Connect but streams real-time progress events (incl. live Journal/
      # Experts log lines) while the connection is established.
      # Requires 'id' header — use GetId to generate.
      # Swagger does not support streaming — use /connect-stream interactive viewer.
      rpc :ConnectStream, ::Mt4TermApi::ConnectRequest, stream(::Mt4TermApi::ConnectStreamEvent)
      # Same as ConnectEx but streams real-time progress events (incl. live Journal/
      # Experts log lines) while the connection is established.
      # Requires 'id' header — use GetId to generate.
      # Swagger does not support streaming — use /connect-stream interactive viewer.
      # [DefaultValues]
      # {
      #   "user": "1124213727",
      #   "password": "1tjvjck",
      #   "mtClusterName": "FreshForex-Demo"
      # }
      rpc :ConnectExStream, ::Mt4TermApi::ConnectExRequest, stream(::Mt4TermApi::ConnectStreamEvent)
    end

    Stub = Service.rpc_stub_class
  end
  module Logs
    # Provides access to terminal log content (Journal and Experts tabs).
    # Reads log entries directly from the MT4 terminal GUI.
    # Requires 'id' header with the terminal connection GUID returned by Connect.
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'mt4_term_api.Logs'

      # Returns log entries from the terminal Journal tab.
      # The Journal tab contains system messages about terminal connection status,
      # network activity, server synchronization and other internal events.
      # Works regardless of which tab is currently active in the terminal UI.
      rpc :Journal, ::Mt4TermApi::JournalRequest, ::Mt4TermApi::JournalReply
      # Streams log entries from the terminal Journal tab in real-time.
      # Requires 'id' header with the terminal connection GUID returned by Connect.
      rpc :OnJournal, ::Mt4TermApi::OnJournalRequest, stream(::Mt4TermApi::OnJournalReply)
      # Returns log entries from the terminal Experts tab.
      # The Experts tab contains messages from Expert Advisors (EAs), scripts and indicators
      # including Print() output, initialization/deinitialization events and runtime errors.
      # Works regardless of which tab is currently active in the terminal UI.
      rpc :Experts, ::Mt4TermApi::JournalRequest, ::Mt4TermApi::JournalReply
      # Streams log entries from the terminal Experts tab in real-time.
      # Requires 'id' header with the terminal connection GUID returned by Connect.
      rpc :OnExperts, ::Mt4TermApi::OnJournalRequest, stream(::Mt4TermApi::OnJournalReply)
    end

    Stub = Service.rpc_stub_class
  end
end
